{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.admin.enabled }}
{{- $adminName := required "externalSecrets.admin.name is required" .Values.externalSecrets.admin.name -}}
{{- $adminTargetName := required "externalSecrets.admin.targetName is required" .Values.externalSecrets.admin.targetName -}}
{{- $adminUsernameRemoteKey := required "externalSecrets.admin.usernameRemoteKey is required" .Values.externalSecrets.admin.usernameRemoteKey -}}
{{- $adminPasswordRemoteKey := required "externalSecrets.admin.passwordRemoteKey is required" .Values.externalSecrets.admin.passwordRemoteKey -}}
{{- $secretStoreName := required "externalSecrets.secretStoreName is required" .Values.externalSecrets.secretStoreName -}}
{{ include "keiailab.secrets.externalSecret" (dict
    "ctx" .
    "name" $adminName
    "labels" (include "mongodb-operator.labels" .)
    "refreshInterval" .Values.externalSecrets.refreshInterval
    "secretStoreKind" .Values.externalSecrets.secretStoreKind
    "secretStoreName" $secretStoreName
    "targetName" $adminTargetName
    "data" (list
      (dict "secretKey" .Values.externalSecrets.admin.usernameKey "remoteKey" $adminUsernameRemoteKey)
      (dict "secretKey" .Values.externalSecrets.admin.passwordKey "remoteKey" $adminPasswordRemoteKey))) }}
{{- end }}
{{ if and .Values.externalSecrets.enabled .Values.externalSecrets.app.enabled }}
{{- $appName := required "externalSecrets.app.name is required" .Values.externalSecrets.app.name -}}
{{- $appTargetName := required "externalSecrets.app.targetName is required" .Values.externalSecrets.app.targetName -}}
{{- $appUsernameRemoteKey := required "externalSecrets.app.usernameRemoteKey is required" .Values.externalSecrets.app.usernameRemoteKey -}}
{{- $appPasswordRemoteKey := required "externalSecrets.app.passwordRemoteKey is required" .Values.externalSecrets.app.passwordRemoteKey -}}
{{- $secretStoreName := required "externalSecrets.secretStoreName is required" .Values.externalSecrets.secretStoreName -}}
---
{{ include "keiailab.secrets.externalSecret" (dict
    "ctx" .
    "name" $appName
    "labels" (include "mongodb-operator.labels" .)
    "refreshInterval" .Values.externalSecrets.refreshInterval
    "secretStoreKind" .Values.externalSecrets.secretStoreKind
    "secretStoreName" $secretStoreName
    "targetName" $appTargetName
    "data" (list
      (dict "secretKey" .Values.externalSecrets.app.usernameKey "remoteKey" $appUsernameRemoteKey)
      (dict "secretKey" .Values.externalSecrets.app.passwordKey "remoteKey" $appPasswordRemoteKey))) }}
{{- end }}
{{ if and .Values.externalSecrets.enabled .Values.externalSecrets.backupS3.enabled }}
{{- $backupS3Name := required "externalSecrets.backupS3.name is required" .Values.externalSecrets.backupS3.name -}}
{{- $backupS3TargetName := required "externalSecrets.backupS3.targetName is required" .Values.externalSecrets.backupS3.targetName -}}
{{- $backupS3AccessKeyRemoteKey := required "externalSecrets.backupS3.accessKeyRemoteKey is required" .Values.externalSecrets.backupS3.accessKeyRemoteKey -}}
{{- $backupS3SecretKeyRemoteKey := required "externalSecrets.backupS3.secretKeyRemoteKey is required" .Values.externalSecrets.backupS3.secretKeyRemoteKey -}}
{{- $secretStoreName := required "externalSecrets.secretStoreName is required" .Values.externalSecrets.secretStoreName -}}
---
{{ include "keiailab.secrets.externalSecret" (dict
    "ctx" .
    "name" $backupS3Name
    "labels" (include "mongodb-operator.labels" .)
    "refreshInterval" .Values.externalSecrets.refreshInterval
    "secretStoreKind" .Values.externalSecrets.secretStoreKind
    "secretStoreName" $secretStoreName
    "targetName" $backupS3TargetName
    "data" (list
      (dict "secretKey" .Values.externalSecrets.backupS3.accessKeyKey "remoteKey" $backupS3AccessKeyRemoteKey)
      (dict "secretKey" .Values.externalSecrets.backupS3.secretKeyKey "remoteKey" $backupS3SecretKeyRemoteKey))) }}
{{- end }}
