apiVersion: cache.keiailab.io/v1alpha1
kind: ValkeyCluster
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cache.keiailab.io/v1alpha1","kind":"ValkeyCluster","metadata":{"annotations":{},"labels":{"argos.io/component":"keiailab-valkey","argos.io/migration-phase":"production-equivalent"},"name":"keiailab-valkey-prod","namespace":"data"},"spec":{"autoFailover":true,"monitoring":{"enabled":true,"serviceMonitor":{"interval":"30s"}},"nodeTimeoutMillis":15000,"persistence":{"aofAppendFsync":"everysec","mode":"Both"},"podDisruptionBudget":{"enabled":true,"minAvailable":3},"replicasPerShard":1,"resources":{"limits":{"cpu":"500m","memory":"1Gi"},"requests":{"cpu":"100m","memory":"256Mi"}},"shards":3,"storage":{"size":"8Gi","storageClassName":"ceph-rbd"},"version":{"image":"docker.io/valkey/valkey","version":"9.0.4"}}}
  finalizers:
  - cache.keiailab.io/valkeycluster-finalizer
  labels:
    argos.io/component: keiailab-valkey
    argos.io/migration-phase: production-equivalent
  name: keiailab-valkey-prod
  namespace: data
spec:
  auth:
    enabled: false
  autoFailover: true
  monitoring:
    enabled: true
    serviceMonitor:
      interval: 30s
  nodeTimeoutMillis: 15000
  persistence:
    aofAppendFsync: everysec
    mode: Both
  podDisruptionBudget:
    enabled: true
    minAvailable: 3
  replicasPerShard: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
  shards: 3
  slotMigration: Auto
  storage:
    dataDirPath: /data
    size: 8Gi
    storageClassName: ceph-rbd
  version:
    image: docker.io/valkey/valkey
    version: 9.0.4
status:
  assignedSlots: 16384
  clusterInitialized: true
  clusterState: ok
  conditions:
  - lastTransitionTime: "2026-05-07T06:14:52Z"
    message: ""
    observedGeneration: 2
    reason: Running
    type: Ready
  - lastTransitionTime: "2026-05-07T09:34:08Z"
    message: ""
    observedGeneration: 2
    reason: ClusterStateOK
    type: ClusterReady
  - lastTransitionTime: "2026-05-07T06:14:52Z"
    message: ""
    observedGeneration: 2
    reason: NoChange
    type: ScalePending
  - lastTransitionTime: "2026-05-07T06:14:52Z"
    message: ""
    observedGeneration: 2
    reason: NoUpgrade
    type: UpgradeInProgress
  - lastTransitionTime: "2026-05-07T06:14:52Z"
    message: ""
    observedGeneration: 2
    reason: TLSDisabled
    type: CertReady
  endpoint: keiailab-valkey-prod.data.svc:6379
  observedGeneration: 2
  phase: Running
  readyReplicas: 6
  shards:
